spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_catalog
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
